type: object
required:
  - _id
  - photo
  - name
  - suppliers
  - stock
  - price
  - category
properties:
  _id:
    description: "Product's id"
    type: string
    example: 65e4decdd286b30065d54af9
  photo:
    description: "Link to product's photo"
    type: string
    format: binary
    example: https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg
  name:
    description: "Product's name"
    type: string
    example: Aspirin
  suppliers:
    description: "Product's suppliers"
    type: string
    example: Square
  stock:
    description: "Product's stock"
    type: string
    example: '12'
  price:
    description: "Product's price"
    type: string
    example: '89.66'
  category:
    description: 'Product category'
    type: string
    enum:
      ['Medicine', 'Heart', 'Head', 'Hand', 'Leg', 'Dental Care', 'Skin Care']
    default: Medicine
    example: Medicine
